apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todoro
resources:
  - namespace.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - ingress.yaml
